### ISSUE TITLE
Removing a middleware

### ISSUE THREAD

**Issue by g7s** [duct-framework/module.web#14]
Instead of the default ring stacktrace middleware in the development environment I wanted to user this one https://github.com/magnars/prone but I cannot find a way to "replace" the `:duct.web.middleware/stacktrace` key in the `:middlewares` of the root handler. Is there any clean way that we can do this?

Thanks

**Comment by weavejester** [comment]
The most straightforward way is to replace the `:middlewares` key with the explicit list of middleware you want.

I've been considering alternative designs that would make it easier to replace default middleware, but currently it can only be done by explicitly choosing the middleware, or by writing a module.

**Comment by g7s** [comment]
That's fine. I ended up getting what middleware are in use in the dev environment 
```clojure
dev> (-> config :duct.handler/root :middleware)
```
and replaced the middleware explicitly. Worked fine! Thank you

**Comment by g7s** [comment]
Here is an idea.
```clojure
:my/alias #ig/override :the/actual-implementation
```
so that would be overridable only when the `:my/alias` key is present?
```clojure
:my/alias {,,,}
```
Does it make sense?

**Comment by weavejester** [comment]
I don't think that's something I'd want to add to Integrant, but I'm also not entirely sure how it helps in this case. Can you explain?

**Comment by g7s** [comment]
Yes ofc. The idea is to be able to override the implementation of a key that exists in a place where that cannot be done "cleanly". For example take the use case of this issue. I know that `:duct.web.middleware/stacktrace`'s implementation is a middleware that is used by the `duct.module-web` that I want to override with another implementation. I could say that
```clojure
:my.project.middleware/stacktrace #ig/overrides :duct.web.middleware/stacktrace
```
in my `main.edn`. Then in my (say) dev profile I could have
```clojure
:my.project.middleware/stacktrace {}
```
where its implementation will be a middleware. 

If we have `merge-configs` be aware of the overrides and replace any reference to `:duct.web.middleware/stacktrace` with a reference to  `:my.project.middleware/stacktrace` (provided that at least one profile implements `:my.project.middleware/stacktrace`) wouldn't that work? I don't know if any of this makes sense with the current state of things in Integrant.

**Comment by weavejester** [comment]
I think it might be better to have a way of removing keys or even nested values when merging. I don't think an override tag is a good fit for Integrant.

**Comment by g7s** [comment]
Fair point. Having a way to remove or replace nested keys / values when merging sounds a better thing to have.
